In [250]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from statsmodels.tsa.stattools import adfuller
from pandas.plotting import autocorrelation_plot
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.tsa.arima_model import ARIMA
from matplotlib.pylab import rcParams

import warnings
warnings.filterwarnings('ignore')

In [251]:
#Ho: It is non stationary
#H1: It is stationary

def adfuller_test(sales):
    result=adfuller(sales)
    labels = ['ADF Test Statistic','p-value','#Lags Used','Number of Observations Used']
    for value,label in zip(result,labels):
        print(label+' : '+str(value) )
    if result[1] <= 0.05:
        print("strong evidence against the null hypothesis(Ho), reject the null hypothesis. Data has no unit root and is stationary")
    else:
        print("weak evidence against null hypothesis, time series has a unit root, indicating it is non-stationary ")

In [252]:
dff_alex_9 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_9["order_dt"] = pd.to_datetime(dff_alex_9["order_dt"],infer_datetime_format=True)
dff_alex_9= dff_alex_9.set_index(["order_dt"])

In [253]:
model_alex_9th=ARIMA(dff_alex_9['9th'],order=(1,1,1))
model_alex_9th_fit=model_alex_9th.fit()
model_alex_9th_forecast= model_alex_9th_fit.forecast(steps = 8)[0]
model_alex_9th_forecast

array([2.29501476, 2.36180132, 2.38282887, 2.39468188, 2.40469542,
       2.41434016, 2.42391095, 2.43346691])

In [254]:
dff_alex_10 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_10["order_dt"] = pd.to_datetime(dff_alex_10["order_dt"],infer_datetime_format=True)
dff_alex_10= dff_alex_10.set_index(["order_dt"])

In [255]:
model_alex_10th=ARIMA(dff_alex_10['10th'],order=(1,1,1))
model_alex_10th_fit=model_alex_10th.fit()
model_alex_10th_forecast= model_alex_10th_fit.forecast(steps = 8)[0]
model_alex_10th_forecast

array([1.70012163, 1.57828599, 1.60808848, 1.60991614, 1.61690471,
       1.62294117, 1.62915328, 1.63533299])

In [256]:
dff_alex_11 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_11["order_dt"] = pd.to_datetime(dff_alex_11["order_dt"],infer_datetime_format=True)
dff_alex_11= dff_alex_11.set_index(["order_dt"])

In [257]:
model_alex_11th=ARIMA(dff_alex_11['11th'],order=(1,1,1))
model_alex_11th_fit=model_alex_11th.fit()
model_alex_11th_forecast= model_alex_11th_fit.forecast(steps = 8)[0]
model_alex_11th_forecast

array([2.75991435, 2.75960766, 2.76975427, 2.78035661, 2.79097882,
       2.80160189, 2.812225  , 2.82284811])

In [258]:
dff_alex_12 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_12["order_dt"] = pd.to_datetime(dff_alex_12["order_dt"],infer_datetime_format=True)
dff_alex_12= dff_alex_12.set_index(["order_dt"])

In [259]:
model_alex_12th=ARIMA(dff_alex_12['12th'],order=(1,1,1))
model_alex_12th_fit=model_alex_12th.fit()
model_alex_12th_forecast= model_alex_12th_fit.forecast(steps = 8)[0]
model_alex_12th_forecast

array([3.11569615, 3.11855402, 3.12815978, 3.13736201, 3.14658837,
       3.15581328, 3.16503829, 3.17426328])

In [260]:
dff_alex_13 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_13["order_dt"] = pd.to_datetime(dff_alex_13["order_dt"],infer_datetime_format=True)
dff_alex_13= dff_alex_13.set_index(["order_dt"])

In [261]:
model_alex_13th=ARIMA(dff_alex_13['13th'],order=(1,1,1))
model_alex_13th_fit=model_alex_13th.fit()
model_alex_13th_forecast= model_alex_13th_fit.forecast(steps = 8)[0]
model_alex_13th_forecast

array([2.69350225, 2.68872961, 2.69698288, 2.70579849, 2.71463838,
       2.72347932, 2.73232031, 2.74116129])

In [262]:
dff_alex_14 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_14["order_dt"] = pd.to_datetime(dff_alex_14["order_dt"],infer_datetime_format=True)
dff_alex_14= dff_alex_14.set_index(["order_dt"])

In [263]:
model_alex_14th=ARIMA(dff_alex_14['14th'],order=(1,1,1))
model_alex_14th_fit=model_alex_14th.fit()
model_alex_14th_forecast= model_alex_14th_fit.forecast(steps = 8)[0]
model_alex_14th_forecast

array([2.49028477, 2.51373167, 2.5215838 , 2.52927013, 2.5369547 ,
       2.54463925, 2.5523238 , 2.56000836])

In [264]:
dff_alex_15 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_15["order_dt"] = pd.to_datetime(dff_alex_15["order_dt"],infer_datetime_format=True)
dff_alex_15= dff_alex_15.set_index(["order_dt"])

In [265]:
model_alex_15th=ARIMA(dff_alex_15['15th'],order=(1,1,1))
model_alex_15th_fit=model_alex_15th.fit()
model_alex_15th_forecast= model_alex_15th_fit.forecast(steps = 8)[0]
model_alex_15th_forecast

array([2.71544687, 2.74521317, 2.75364406, 2.7618049 , 2.76996234,
       2.77811972, 2.78627711, 2.7944345 ])

In [266]:
dff_alex_16 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_16["order_dt"] = pd.to_datetime(dff_alex_16["order_dt"],infer_datetime_format=True)
dff_alex_16= dff_alex_16.set_index(["order_dt"])

In [267]:
model_alex_16th=ARIMA(dff_alex_16['16th'],order=(1,1,1))
model_alex_16th_fit=model_alex_16th.fit()
model_alex_16th_forecast= model_alex_16th_fit.forecast(steps = 8)[0]
model_alex_16th_forecast

array([3.13276883, 3.13958058, 3.15111646, 3.16247516, 3.1738405 ,
       3.1852056 , 3.1965707 , 3.2079358 ])

In [268]:
dff_alex_17 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_17["order_dt"] = pd.to_datetime(dff_alex_17["order_dt"],infer_datetime_format=True)
dff_alex_17= dff_alex_17.set_index(["order_dt"])

In [269]:
model_alex_17th=ARIMA(dff_alex_17['17th'],order=(1,1,1))
model_alex_17th_fit=model_alex_17th.fit()
model_alex_17th_forecast= model_alex_17th_fit.forecast(steps = 8)[0]
model_alex_17th_forecast

array([4.08446229, 4.22828517, 4.25249333, 4.26932883, 4.28570989,
       4.30206295, 4.31841428, 4.33476551])

In [270]:
dff_alex_18 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_18["order_dt"] = pd.to_datetime(dff_alex_18["order_dt"],infer_datetime_format=True)
dff_alex_18= dff_alex_18.set_index(["order_dt"])

In [271]:
model_alex_18th=ARIMA(dff_alex_18['18th'],order=(1,1,1))
model_alex_18th_fit=model_alex_18th.fit()
model_alex_18th_forecast= model_alex_18th_fit.forecast(steps = 8)[0]
model_alex_18th_forecast

array([4.81070105, 4.81633144, 4.83102418, 4.84613823, 4.86127187,
       4.87640642, 4.89154101, 4.90667561])

In [272]:
dff_alex_19 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_19["order_dt"] = pd.to_datetime(dff_alex_19["order_dt"],infer_datetime_format=True)
dff_alex_19= dff_alex_19.set_index(["order_dt"])

In [273]:
model_alex_19th=ARIMA(dff_alex_19['19th'],order=(1,1,1))
model_alex_19th_fit=model_alex_19th.fit()
model_alex_19th_forecast= model_alex_19th_fit.forecast(steps = 8)[0]
model_alex_19th_forecast

array([3.77689927, 3.90178281, 3.92342021, 3.93860502, 3.95338657,
       3.96814291, 3.98289768, 3.99765235])

In [274]:
dff_alex_20 = pd.read_excel("ALEXANDRIA.xlsx")
dff_alex_20["order_dt"] = pd.to_datetime(dff_alex_20["order_dt"],infer_datetime_format=True)
dff_alex_20= dff_alex_20.set_index(["order_dt"])

In [275]:
model_alex_20th=ARIMA(dff_alex_20['20th'],order=(1,1,1))
model_alex_20th_fit=model_alex_20th.fit()
model_alex_20th_forecast= model_alex_20th_fit.forecast(steps = 8)[0]
model_alex_20th_forecast

array([3.36031442, 3.38786816, 3.4012621 , 3.4140535 , 3.42681927,
       3.43958395, 3.45234858, 3.4651132 ])

In [276]:
data_alex = [k for k in zip(model_alex_9th_forecast,model_alex_10th_forecast,model_alex_11th_forecast,
                           model_alex_12th_forecast,model_alex_13th_forecast,model_alex_14th_forecast,
                 model_alex_15th_forecast,model_alex_16th_forecast,model_alex_17th_forecast,model_alex_18th_forecast,
                            model_alex_19th_forecast,model_alex_20th_forecast
                           )]

In [277]:
dff_alex = pd.DataFrame(data_alex)
dff_alex.head(10)

0         1         2         3         4         5         6   \
0  2.295015  1.700122  2.759914  3.115696  2.693502  2.490285  2.715447   
1  2.361801  1.578286  2.759608  3.118554  2.688730  2.513732  2.745213   
2  2.382829  1.608088  2.769754  3.128160  2.696983  2.521584  2.753644   
3  2.394682  1.609916  2.780357  3.137362  2.705798  2.529270  2.761805   
4  2.404695  1.616905  2.790979  3.146588  2.714638  2.536955  2.769962   
5  2.414340  1.622941  2.801602  3.155813  2.723479  2.544639  2.778120   
6  2.423911  1.629153  2.812225  3.165038  2.732320  2.552324  2.786277   
7  2.433467  1.635333  2.822848  3.174263  2.741161  2.560008  2.794434   

         7         8         9         10        11  
0  3.132769  4.084462  4.810701  3.776899  3.360314  
1  3.139581  4.228285  4.816331  3.901783  3.387868  
2  3.151116  4.252493  4.831024  3.923420  3.401262  
3  3.162475  4.269329  4.846138  3.938605  3.414054  
4  3.173841  4.285710  4.861272  3.953387  3.426819  
5  3.185206  4.302063  4.876406  3.968143  3.439584  
6  3.196571  4.318414  4.891541  3.982898  3.452349  
7  3.207936  4.334766  4.906676  3.997652  3.465113

In [278]:
dff_alex.to_excel('alex_test_2m_9m.xlsx')

In [279]:
df_colng_9 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_9["order_dt"] = pd.to_datetime(df_colng_9["order_dt"],infer_datetime_format=True)
df_colng_9= df_colng_9.set_index(["order_dt"])

In [280]:
model_colng_9th=ARIMA(df_colng_9['9th'],order=(1,1,1))
model_colng_9th_fit=model_colng_9th.fit()
model_colng_9th_forecast= model_colng_9th_fit.forecast(steps = 8)[0]
model_colng_9th_forecast

array([2.89019617, 3.07547043, 3.10745533, 3.12565799, 3.1426215 ,
       3.15947359, 3.17631567, 3.19315684])

In [281]:
df_colng_10 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_10["order_dt"] = pd.to_datetime(df_colng_10["order_dt"],infer_datetime_format=True)
df_colng_10= df_colng_10.set_index(["order_dt"])

In [282]:
model_colng_10th=ARIMA(df_colng_10['10th'],order=(1,1,1))
model_colng_10th_fit=model_colng_10th.fit()
model_colng_10th_forecast= model_colng_10th_fit.forecast(steps = 8)[0]
model_colng_10th_forecast

array([2.23291651, 2.26292508, 2.27685907, 2.28951963, 2.3020793 ,
       2.31463098, 2.32718202, 2.33973302])

In [283]:
df_colng_11 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_11["order_dt"] = pd.to_datetime(df_colng_11["order_dt"],infer_datetime_format=True)
df_colng_11= df_colng_11.set_index(["order_dt"])

In [284]:
model_colng_11th=ARIMA(df_colng_11['11th'],order=(1,1,1))
model_colng_11th_fit=model_colng_11th.fit()
model_colng_11th_forecast= model_colng_11th_fit.forecast(steps = 8)[0]
model_colng_11th_forecast

array([3.23205841, 3.24786144, 3.26424374, 3.28062448, 3.29700522,
       3.31338597, 3.32976671, 3.34614746])

In [285]:
df_colng_12 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_12["order_dt"] = pd.to_datetime(df_colng_12["order_dt"],infer_datetime_format=True)
df_colng_12= df_colng_12.set_index(["order_dt"])

In [286]:
model_colng_12th=ARIMA(df_colng_12['12th'],order=(1,1,1))
model_colng_12th_fit=model_colng_12th.fit()
model_colng_12th_forecast= model_colng_12th_fit.forecast(steps = 8)[0]
model_colng_12th_forecast

array([2.56706727, 2.59192013, 2.6058211 , 2.61998407, 2.63414078,
       2.64829763, 2.66245448, 2.67661134])

In [287]:
df_colng_13 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_13["order_dt"] = pd.to_datetime(df_colng_13["order_dt"],infer_datetime_format=True)
df_colng_13= df_colng_13.set_index(["order_dt"])

In [288]:
model_colng_13th=ARIMA(df_colng_13['13th'],order=(1,1,1))
model_colng_13th_fit=model_colng_13th.fit()
model_colng_13th_forecast= model_colng_13th_fit.forecast(steps = 8)[0]
model_colng_13th_forecast

array([2.87577757, 2.8852704 , 2.89874548, 2.91233916, 2.92593638,
       2.9395337 , 2.95313102, 2.96672834])

In [289]:
df_colng_14 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_14["order_dt"] = pd.to_datetime(df_colng_14["order_dt"],infer_datetime_format=True)
df_colng_14= df_colng_14.set_index(["order_dt"])

In [290]:
model_colng_14th=ARIMA(df_colng_14['14th'],order=(1,1,1))
model_colng_14th_fit=model_colng_14th.fit()
model_colng_14th_forecast= model_colng_14th_fit.forecast(steps = 8)[0]
model_colng_14th_forecast

array([3.10851103, 3.1099483 , 3.12695842, 3.14374949, 3.16054364,
       3.17733774, 3.19413185, 3.21092595])

In [291]:
df_colng_15 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_15["order_dt"] = pd.to_datetime(df_colng_15["order_dt"],infer_datetime_format=True)
df_colng_15= df_colng_15.set_index(["order_dt"])

In [292]:
model_colng_15th=ARIMA(df_colng_15['15th'],order=(1,1,1))
model_colng_15th_fit=model_colng_15th.fit()
model_colng_15th_forecast= model_colng_15th_fit.forecast(steps = 8)[0]
model_colng_15th_forecast

array([2.93199754, 2.94763229, 2.95958368, 2.9715476 , 2.98351147,
       2.99547535, 3.00743922, 3.0194031 ])

In [293]:
df_colng_16 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_16["order_dt"] = pd.to_datetime(df_colng_16["order_dt"],infer_datetime_format=True)
df_colng_16= df_colng_16.set_index(["order_dt"])

In [294]:
model_colng_16th=ARIMA(df_colng_16['16th'],order=(1,1,1))
model_colng_16th_fit=model_colng_16th.fit()
model_colng_16th_forecast= model_colng_16th_fit.forecast(steps = 8)[0]
model_colng_16th_forecast

array([4.32853331, 4.27869536, 4.29534198, 4.31909926, 4.34361704,
       4.36821616, 4.39282398, 4.41743273])

In [295]:
df_colng_17 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_17["order_dt"] = pd.to_datetime(df_colng_17["order_dt"],infer_datetime_format=True)
df_colng_17= df_colng_17.set_index(["order_dt"])

In [296]:
model_colng_17th=ARIMA(df_colng_17['17th'],order=(1,1,1))
model_colng_17th_fit=model_colng_17th.fit()
model_colng_17th_forecast= model_colng_17th_fit.forecast(steps = 8)[0]
model_colng_17th_forecast

array([5.01051077, 5.03711897, 5.06447256, 5.09186066, 5.11925035,
       5.14664012, 5.1740299 , 5.20141967])

In [297]:
df_colng_18 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_18["order_dt"] = pd.to_datetime(df_colng_18["order_dt"],infer_datetime_format=True)
df_colng_18= df_colng_18.set_index(["order_dt"])

In [298]:
model_colng_18th=ARIMA(df_colng_18['18th'],order=(1,1,1))
model_colng_18th_fit=model_colng_18th.fit()
model_colng_18th_forecast= model_colng_18th_fit.forecast(steps = 8)[0]
model_colng_18th_forecast

array([4.47517961, 4.54918754, 4.58046306, 4.60718677, 4.63342563,
       4.65961284, 4.68579455, 4.71197567])

In [299]:
df_colng_19 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_19["order_dt"] = pd.to_datetime(df_colng_19["order_dt"],infer_datetime_format=True)
df_colng_19= df_colng_19.set_index(["order_dt"])

In [300]:
model_colng_19th=ARIMA(df_colng_19['19th'],order=(1,1,1))
model_colng_19th_fit=model_colng_19th.fit()
model_colng_19th_forecast= model_colng_19th_fit.forecast(steps = 8)[0]
model_colng_19th_forecast

array([4.68896976, 4.68192927, 4.70717208, 4.7321329 , 4.75709618,
       4.78205944, 4.8070227 , 4.83198596])

In [301]:
df_colng_20 = pd.read_excel("COLLINGWOOD.xlsx")
df_colng_20["order_dt"] = pd.to_datetime(df_colng_20["order_dt"],infer_datetime_format=True)
df_colng_20= df_colng_20.set_index(["order_dt"])

In [302]:
model_colng_20th=ARIMA(df_colng_20['20th'],order=(1,1,1))
model_colng_20th_fit=model_colng_20th.fit()
model_colng_20th_forecast= model_colng_20th_fit.forecast(steps = 8)[0]
model_colng_20th_forecast

array([3.60765358, 3.60477659, 3.62349461, 3.64341002, 3.66339182,
       3.68337731, 3.703363  , 3.72334869])

In [303]:
data_colng =[k for k in zip(model_colng_9th_forecast,model_colng_10th_forecast,
                            model_colng_11th_forecast,model_colng_12th_forecast,model_colng_13th_forecast,
                           model_colng_14th_forecast,model_colng_15th_forecast,model_colng_16th_forecast,
                           model_colng_17th_forecast,model_colng_18th_forecast,model_colng_19th_forecast,
                           model_colng_20th_forecast)]

In [304]:
df_colng = pd.DataFrame(data_colng)
df_colng.head(10)

0         1         2         3         4         5         6   \
0  2.890196  2.232917  3.232058  2.567067  2.875778  3.108511  2.931998   
1  3.075470  2.262925  3.247861  2.591920  2.885270  3.109948  2.947632   
2  3.107455  2.276859  3.264244  2.605821  2.898745  3.126958  2.959584   
3  3.125658  2.289520  3.280624  2.619984  2.912339  3.143749  2.971548   
4  3.142621  2.302079  3.297005  2.634141  2.925936  3.160544  2.983511   
5  3.159474  2.314631  3.313386  2.648298  2.939534  3.177338  2.995475   
6  3.176316  2.327182  3.329767  2.662454  2.953131  3.194132  3.007439   
7  3.193157  2.339733  3.346147  2.676611  2.966728  3.210926  3.019403   

         7         8         9         10        11  
0  4.328533  5.010511  4.475180  4.688970  3.607654  
1  4.278695  5.037119  4.549188  4.681929  3.604777  
2  4.295342  5.064473  4.580463  4.707172  3.623495  
3  4.319099  5.091861  4.607187  4.732133  3.643410  
4  4.343617  5.119250  4.633426  4.757096  3.663392  
5  4.368216  5.146640  4.659613  4.782059  3.683377  
6  4.392824  5.174030  4.685795  4.807023  3.703363  
7  4.417433  5.201420  4.711976  4.831986  3.723349

In [305]:
df_colng.to_excel('colng_2m_9m_test.xlsx')

In [306]:
df_potts_9 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_9["order_dt"] = pd.to_datetime(df_potts_9["order_dt"],infer_datetime_format=True)
df_potts_9= df_potts_9.set_index(["order_dt"])

In [307]:
model_potts_9th=ARIMA(df_potts_9['potts_9th'],order=(1,1,1))
model_potts_9th_fit=model_potts_9th.fit()
model_potts_9th_forecast= model_potts_9th_fit.forecast(steps = 8)[0]
model_potts_9th_forecast

array([1.98793225, 2.26215473, 2.34424539, 2.37461385, 2.39105861,
       2.40375508, 2.41544251, 2.4268583 ])

In [308]:
df_potts_10 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_10["order_dt"] = pd.to_datetime(df_potts_10["order_dt"],infer_datetime_format=True)
df_potts_10= df_potts_10.set_index(["order_dt"])

In [309]:
model_potts_10th=ARIMA(df_potts_10['potts_10th'],order=(1,1,1))
model_potts_10th_fit=model_potts_10th.fit()
model_potts_10th_forecast= model_potts_10th_fit.forecast(steps = 8)[0]
model_potts_10th_forecast

array([2.40951749, 2.15309954, 2.11858499, 2.12098103, 2.12951665,
       2.1390735 , 2.14880022, 2.1585552 ])

In [310]:
df_potts_11 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_11["order_dt"] = pd.to_datetime(df_potts_11["order_dt"],infer_datetime_format=True)
df_potts_11= df_potts_11.set_index(["order_dt"])

In [311]:
model_potts_11th=ARIMA(df_potts_11['potts_11th'],order=(1,1,1))
model_potts_11th_fit=model_potts_11th.fit()
model_potts_11th_forecast= model_potts_11th_fit.forecast(steps = 8)[0]
model_potts_11th_forecast

array([2.45838   , 2.4525194 , 2.46472251, 2.47753467, 2.49036736,
       2.50320074, 2.51603414, 2.52886755])

In [312]:
df_potts_12 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_12["order_dt"] = pd.to_datetime(df_potts_12["order_dt"],infer_datetime_format=True)
df_potts_12= df_potts_12.set_index(["order_dt"])

In [313]:
model_potts_12th=ARIMA(df_potts_12['potts_12th'],order=(1,1,1))
model_potts_12th_fit=model_potts_12th.fit()
model_potts_12th_forecast= model_potts_12th_fit.forecast(steps = 8)[0]
model_potts_12th_forecast

array([2.72354158, 2.68219573, 2.68494461, 2.69596334, 2.70853305,
       2.72139365, 2.73430881, 2.7472342 ])

In [314]:
df_potts_13 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_13["order_dt"] = pd.to_datetime(df_potts_13["order_dt"],infer_datetime_format=True)
df_potts_13= df_potts_13.set_index(["order_dt"])

In [315]:
model_potts_13th=ARIMA(df_potts_13['potts_13th'],order=(1,1,1))
model_potts_13th_fit=model_potts_13th.fit()
model_potts_13th_forecast= model_potts_13th_fit.forecast(steps = 8)[0]
model_potts_13th_forecast

array([2.25905956, 2.27785831, 2.28936624, 2.30083132, 2.31229614,
       2.32376096, 2.33522578, 2.3466906 ])

In [316]:
df_potts_14 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_14["order_dt"] = pd.to_datetime(df_potts_14["order_dt"],infer_datetime_format=True)
df_potts_14= df_potts_14.set_index(["order_dt"])

In [317]:
model_potts_14th=ARIMA(df_potts_14['potts_14th'],order=(1,1,1))
model_potts_14th_fit=model_potts_14th.fit()
model_potts_14th_forecast= model_potts_14th_fit.forecast(steps = 8)[0]
model_potts_14th_forecast

array([3.01067367, 3.02683339, 3.04229107, 3.05783859, 3.07337461,
       3.0889121 , 3.10444941, 3.11998674])

In [318]:
df_potts_15 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_15["order_dt"] = pd.to_datetime(df_potts_15["order_dt"],infer_datetime_format=True)
df_potts_15= df_potts_15.set_index(["order_dt"])

In [319]:
model_potts_15th=ARIMA(df_potts_15['potts_15th'],order=(1,1,1))
model_potts_15th_fit=model_potts_15th.fit()
model_potts_15th_forecast= model_potts_15th_fit.forecast(steps = 8)[0]
model_potts_15th_forecast

array([1.99551722, 2.00625883, 2.01623954, 2.02625829, 2.03627513,
       2.04629206, 2.056309  , 2.06632593])

In [320]:
df_potts_16 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_16["order_dt"] = pd.to_datetime(df_potts_16["order_dt"],infer_datetime_format=True)
df_potts_16= df_potts_16.set_index(["order_dt"])

In [321]:
model_potts_16th=ARIMA(df_potts_16['potts_16th'],order=(1,1,1))
model_potts_16th_fit=model_potts_16th.fit()
model_potts_16th_forecast= model_potts_16th_fit.forecast(steps = 8)[0]
model_potts_16th_forecast

array([3.34556052, 3.77533276, 3.74769249, 3.77128027, 3.78913075,
       3.80762378, 3.82604485, 3.84447398])

In [322]:
df_potts_17 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_17["order_dt"] = pd.to_datetime(df_potts_17["order_dt"],infer_datetime_format=True)
df_potts_17= df_potts_17.set_index(["order_dt"])

In [323]:
model_potts_17th=ARIMA(df_potts_17['potts_17th'],order=(1,1,1))
model_potts_17th_fit=model_potts_17th.fit()
model_potts_17th_forecast= model_potts_17th_fit.forecast(steps = 8)[0]
model_potts_17th_forecast

array([4.37801684, 4.37803569, 4.40163656, 4.42376622, 4.44598768,
       4.4682034 , 4.49041948, 4.51263554])

In [324]:
df_potts_18 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_18["order_dt"] = pd.to_datetime(df_potts_18["order_dt"],infer_datetime_format=True)
df_potts_18= df_potts_18.set_index(["order_dt"])

In [325]:
model_potts_18th=ARIMA(df_potts_18['potts_18th'],order=(1,1,1))
model_potts_18th_fit=model_potts_18th.fit()
model_potts_18th_forecast= model_potts_18th_fit.forecast(steps = 8)[0]
model_potts_18th_forecast

array([5.20438392, 5.38339684, 5.42982006, 5.45909824, 5.48615941,
       5.5129339 , 5.53967132, 5.56640395])

In [326]:
df_potts_19 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_19["order_dt"] = pd.to_datetime(df_potts_19["order_dt"],infer_datetime_format=True)
df_potts_19= df_potts_19.set_index(["order_dt"])

In [327]:
model_potts_19th=ARIMA(df_potts_19['potts_19th'],order=(1,1,1))
model_potts_19th_fit=model_potts_19th.fit()
model_potts_19th_forecast= model_potts_19th_fit.forecast(steps = 8)[0]
model_potts_19th_forecast

array([5.61584639, 5.96556485, 6.02253884, 6.05327402, 6.08165741,
       6.10983   , 6.1379837 , 6.16613571])

In [328]:
df_potts_20 = pd.read_excel("POTTSPOINT.xlsx")
df_potts_20["order_dt"] = pd.to_datetime(df_potts_20["order_dt"],infer_datetime_format=True)
df_potts_20= df_potts_20.set_index(["order_dt"])

In [329]:
model_potts_20th=ARIMA(df_potts_20['potts_20th'],order=(1,1,1))
model_potts_20th_fit=model_potts_20th.fit()
model_potts_20th_forecast= model_potts_20th_fit.forecast(steps = 8)[0]
model_potts_20th_forecast

array([2.52008945, 2.52210475, 2.53344672, 2.54473138, 2.5560164 ,
       2.56730141, 2.57858642, 2.58987143])

In [330]:
data_potts = [k for k in zip(model_potts_9th_forecast,model_potts_10th_forecast,
                             model_potts_11th_forecast,model_potts_12th_forecast,model_potts_13th_forecast,
                            model_potts_14th_forecast,model_potts_15th_forecast,model_potts_16th_forecast,
                             model_potts_17th_forecast,model_potts_18th_forecast,model_potts_19th_forecast,
                            model_potts_20th_forecast)]

In [331]:
df_potts = pd.DataFrame(data_potts)
df_potts.head(10)

0         1         2         3         4         5         6   \
0  1.987932  2.409517  2.458380  2.723542  2.259060  3.010674  1.995517   
1  2.262155  2.153100  2.452519  2.682196  2.277858  3.026833  2.006259   
2  2.344245  2.118585  2.464723  2.684945  2.289366  3.042291  2.016240   
3  2.374614  2.120981  2.477535  2.695963  2.300831  3.057839  2.026258   
4  2.391059  2.129517  2.490367  2.708533  2.312296  3.073375  2.036275   
5  2.403755  2.139074  2.503201  2.721394  2.323761  3.088912  2.046292   
6  2.415443  2.148800  2.516034  2.734309  2.335226  3.104449  2.056309   
7  2.426858  2.158555  2.528868  2.747234  2.346691  3.119987  2.066326   

         7         8         9         10        11  
0  3.345561  4.378017  5.204384  5.615846  2.520089  
1  3.775333  4.378036  5.383397  5.965565  2.522105  
2  3.747692  4.401637  5.429820  6.022539  2.533447  
3  3.771280  4.423766  5.459098  6.053274  2.544731  
4  3.789131  4.445988  5.486159  6.081657  2.556016  
5  3.807624  4.468203  5.512934  6.109830  2.567301  
6  3.826045  4.490419  5.539671  6.137984  2.578586  
7  3.844474  4.512636  5.566404  6.166136  2.589871

In [332]:
df_potts.to_excel('potts_2m_9m_test.xlsx')

In [333]:
df_smb_9 = pd.read_excel("SMB.xlsx")
df_smb_9["order_dt"] = pd.to_datetime(df_smb_9["order_dt"],infer_datetime_format=True)
df_smb_9= df_smb_9.set_index(["order_dt"])

In [334]:
model_smb_9th=ARIMA(df_smb_9['9th'],order=(1,1,1))
model_smb_9th_fit=model_smb_9th.fit()
model_smb_9th_forecast= model_smb_9th_fit.forecast(steps = 8)[0]
model_smb_9th_forecast

array([1.3180557 , 1.35763244, 1.36717975, 1.37348887, 1.3794488 ,
       1.38537108, 1.3912893 , 1.39720709])

In [335]:
df_smb_10 = pd.read_excel("SMB.xlsx")
df_smb_10["order_dt"] = pd.to_datetime(df_smb_10["order_dt"],infer_datetime_format=True)
df_smb_10= df_smb_10.set_index(["order_dt"])

In [336]:
model_smb_10th=ARIMA(df_smb_10['10th'],order=(1,1,1))
model_smb_10th_fit=model_smb_10th.fit()
model_smb_10th_forecast= model_smb_10th_fit.forecast(steps = 8)[0]
model_smb_10th_forecast

array([1.69419156, 1.7696521 , 1.7829512 , 1.79000519, 1.79643175,
       1.80279528, 1.80915248, 1.81550904])

In [337]:
df_smb_11 = pd.read_excel("SMB.xlsx")
df_smb_11["order_dt"] = pd.to_datetime(df_smb_11["order_dt"],infer_datetime_format=True)
df_smb_11= df_smb_11.set_index(["order_dt"])

In [338]:
model_smb_11th=ARIMA(df_smb_11['11th'],order=(1,1,1))
model_smb_11th_fit=model_smb_11th.fit()
model_smb_11th_forecast= model_smb_11th_fit.forecast(steps = 8)[0]
model_smb_11th_forecast

array([1.80081294, 1.77447316, 1.77516894, 1.78009343, 1.78567934,
       1.79136872, 1.79707427, 1.80278235])

In [339]:
df_smb_12 = pd.read_excel("SMB.xlsx")
df_smb_12["order_dt"] = pd.to_datetime(df_smb_12["order_dt"],infer_datetime_format=True)
df_smb_12= df_smb_12.set_index(["order_dt"])

In [340]:
model_smb_12th=ARIMA(df_smb_12['12th'],order=(1,1,1))
model_smb_12th_fit=model_smb_12th.fit()
model_smb_12th_forecast= model_smb_12th_fit.forecast(steps = 8)[0]
model_smb_12th_forecast

array([1.60398288, 1.63467516, 1.63956238, 1.64601016, 1.65236355,
       1.65872266, 1.66508142, 1.67144021])

In [341]:
df_smb_13 = pd.read_excel("SMB.xlsx")
df_smb_13["order_dt"] = pd.to_datetime(df_smb_13["order_dt"],infer_datetime_format=True)
df_smb_13= df_smb_13.set_index(["order_dt"])

In [342]:
model_smb_13th=ARIMA(df_smb_13['13th'],order=(1,1,1))
model_smb_13th_fit=model_smb_13th.fit()
model_smb_13th_forecast= model_smb_13th_fit.forecast(steps = 8)[0]
model_smb_13th_forecast

array([1.88501484, 1.78600648, 1.79737994, 1.80261227, 1.80818627,
       1.81374125, 1.8192973 , 1.82485328])

In [343]:
df_smb_14 = pd.read_excel("SMB.xlsx")
df_smb_14["order_dt"] = pd.to_datetime(df_smb_14["order_dt"],infer_datetime_format=True)
df_smb_14= df_smb_14.set_index(["order_dt"])

In [344]:
model_smb_14th=ARIMA(df_smb_14['14th'],order=(1,1,1))
model_smb_14th_fit=model_smb_14th.fit()
model_smb_14th_forecast= model_smb_14th_fit.forecast(steps = 8)[0]
model_smb_14th_forecast

array([2.07254323, 2.08096874, 2.08869533, 2.09641429, 2.10413317,
       2.11185205, 2.11957093, 2.12728981])

In [345]:
df_smb_15 = pd.read_excel("SMB.xlsx")
df_smb_15["order_dt"] = pd.to_datetime(df_smb_15["order_dt"],infer_datetime_format=True)
df_smb_15= df_smb_15.set_index(["order_dt"])

In [346]:
model_smb_15th=ARIMA(df_smb_15['15th'],order=(1,1,1))
model_smb_15th_fit=model_smb_15th.fit()
model_smb_15th_forecast= model_smb_15th_fit.forecast(steps = 8)[0]
model_smb_15th_forecast

array([2.70365512, 2.56209091, 2.57844227, 2.58602898, 2.59410215,
       2.60214832, 2.61019599, 2.61824357])

In [347]:
df_smb_16 = pd.read_excel("SMB.xlsx")
df_smb_16["order_dt"] = pd.to_datetime(df_smb_16["order_dt"],infer_datetime_format=True)
df_smb_16= df_smb_16.set_index(["order_dt"])

In [348]:
model_smb_16th=ARIMA(df_smb_16['16th'],order=(1,1,1))
model_smb_16th_fit=model_smb_16th.fit()
model_smb_16th_forecast= model_smb_16th_fit.forecast(steps = 8)[0]
model_smb_16th_forecast

array([2.13271872, 2.19433168, 2.19767737, 2.20467802, 2.2114494 ,
       2.21823517, 2.22502003, 2.23180495])

In [349]:
df_smb_17 = pd.read_excel("SMB.xlsx")
df_smb_17["order_dt"] = pd.to_datetime(df_smb_17["order_dt"],infer_datetime_format=True)
df_smb_17= df_smb_17.set_index(["order_dt"])

In [350]:
model_smb_17th=ARIMA(df_smb_17['17th'],order=(1,1,1))
model_smb_17th_fit=model_smb_17th.fit()
model_smb_17th_forecast= model_smb_17th_fit.forecast(steps = 8)[0]
model_smb_17th_forecast

array([3.52782933, 3.52936024, 3.54376545, 3.55785572, 3.5719537 ,
       3.58605149, 3.60014928, 3.61424707])

In [351]:
df_smb_18 = pd.read_excel("SMB.xlsx")
df_smb_18["order_dt"] = pd.to_datetime(df_smb_18["order_dt"],infer_datetime_format=True)
df_smb_18= df_smb_18.set_index(["order_dt"])

In [352]:
model_smb_18th=ARIMA(df_smb_18['18th'],order=(1,1,1))
model_smb_18th_fit=model_smb_18th.fit()
model_smb_18th_forecast= model_smb_18th_fit.forecast(steps = 8)[0]
model_smb_18th_forecast

array([3.76982765, 3.78104479, 3.79510751, 3.80916563, 3.82322375,
       3.83728188, 3.85134   , 3.86539812])

In [353]:
df_smb_19 = pd.read_excel("SMB.xlsx")
df_smb_19["order_dt"] = pd.to_datetime(df_smb_19["order_dt"],infer_datetime_format=True)
df_smb_19= df_smb_19.set_index(["order_dt"])

In [354]:
model_smb_19th=ARIMA(df_smb_19['19th'],order=(1,1,1))
model_smb_19th_fit=model_smb_19th.fit()
model_smb_19th_forecast= model_smb_19th_fit.forecast(steps = 8)[0]
model_smb_19th_forecast

array([3.35816411, 3.88541281, 4.01313094, 4.05366608, 4.07517672,
       4.09253595, 4.10898928, 4.12524494])

In [355]:
df_smb_20 = pd.read_excel("SMB.xlsx")
df_smb_20["order_dt"] = pd.to_datetime(df_smb_20["order_dt"],infer_datetime_format=True)
df_smb_20= df_smb_20.set_index(["order_dt"])

In [356]:
model_smb_20th=ARIMA(df_smb_20['20th'],order=(1,1,1))
model_smb_20th_fit=model_smb_20th.fit()
model_smb_20th_forecast= model_smb_20th_fit.forecast(steps = 8)[0]
model_smb_20th_forecast

array([2.15172632, 2.45148715, 2.50089389, 2.51645704, 2.52744511,
       2.53781471, 2.5481007 , 2.5583754 ])

In [357]:
data_smb =[k for k in zip(model_smb_9th_forecast,model_smb_10th_forecast,model_smb_11th_forecast,
                      model_smb_12th_forecast,model_smb_13th_forecast,model_smb_14th_forecast,model_smb_15th_forecast,
                      model_smb_16th_forecast,model_smb_17th_forecast,model_smb_18th_forecast,model_smb_19th_forecast,
                      model_smb_20th_forecast)]


In [358]:

df_smb = pd.DataFrame(data_smb)
df_smb.head(10)

0         1         2         3         4         5         6   \
0  1.318056  1.694192  1.800813  1.603983  1.885015  2.072543  2.703655   
1  1.357632  1.769652  1.774473  1.634675  1.786006  2.080969  2.562091   
2  1.367180  1.782951  1.775169  1.639562  1.797380  2.088695  2.578442   
3  1.373489  1.790005  1.780093  1.646010  1.802612  2.096414  2.586029   
4  1.379449  1.796432  1.785679  1.652364  1.808186  2.104133  2.594102   
5  1.385371  1.802795  1.791369  1.658723  1.813741  2.111852  2.602148   
6  1.391289  1.809152  1.797074  1.665081  1.819297  2.119571  2.610196   
7  1.397207  1.815509  1.802782  1.671440  1.824853  2.127290  2.618244   

         7         8         9         10        11  
0  2.132719  3.527829  3.769828  3.358164  2.151726  
1  2.194332  3.529360  3.781045  3.885413  2.451487  
2  2.197677  3.543765  3.795108  4.013131  2.500894  
3  2.204678  3.557856  3.809166  4.053666  2.516457  
4  2.211449  3.571954  3.823224  4.075177  2.527445  
5  2.218235  3.586051  3.837282  4.092536  2.537815  
6  2.225020  3.600149  3.851340  4.108989  2.548101  
7  2.231805  3.614247  3.865398  4.125245  2.558375

In [360]:
df_smb.to_excel('smb_2m_9m_test.xlsx')

In [361]:
df_andl_9 = pd.read_excel("ANNANDALE.xlsx")
df_andl_9["order_dt"] = pd.to_datetime(df_andl_9["order_dt"],infer_datetime_format=True)
df_andl_9= df_andl_9.set_index(["order_dt"])

In [362]:
model_andl_9th=ARIMA(df_andl_9['9th'],order=(1,1,0))
model_andl_9th_fit=model_andl_9th.fit()
model_andl_9th_forecast= model_andl_9th_fit.forecast(steps = 8)[0]
model_andl_9th_forecast

array([1.21543155, 0.72441213, 0.92418199, 0.84431309, 0.8776449 ,
       0.86515187, 0.87120922, 0.86975718])

In [363]:
df_andl_10 = pd.read_excel("ANNANDALE.xlsx")
df_andl_10["order_dt"] = pd.to_datetime(df_andl_10["order_dt"],infer_datetime_format=True)
df_andl_10= df_andl_10.set_index(["order_dt"])

In [364]:
model_andl_10th=ARIMA(df_andl_10['10th'],order=(1,1,1))
model_andl_10th_fit=model_andl_10th.fit()
model_andl_10th_forecast= model_andl_10th_fit.forecast(steps = 8)[0]
model_andl_10th_forecast

array([2.49946179, 2.51914776, 2.5276411 , 2.53587333, 2.54409946,
       2.55232546, 2.56055145, 2.56877744])

In [365]:
df_andl_11 = pd.read_excel("ANNANDALE.xlsx")
df_andl_11["order_dt"] = pd.to_datetime(df_andl_11["order_dt"],infer_datetime_format=True)
df_andl_11= df_andl_11.set_index(["order_dt"])

In [366]:
model_andl_11th=ARIMA(df_andl_11['11th'],order=(1,1,1))
model_andl_11th_fit=model_andl_11th.fit()
model_andl_11th_forecast= model_andl_11th_fit.forecast(steps = 8)[0]
model_andl_11th_forecast

array([2.46219945, 2.48672274, 2.49597935, 2.50565044, 2.51531028,
       2.52497042, 2.53463056, 2.54429069])

In [367]:
df_andl_12 = pd.read_excel("ANNANDALE.xlsx")
df_andl_12["order_dt"] = pd.to_datetime(df_andl_12["order_dt"],infer_datetime_format=True)
df_andl_12= df_andl_12.set_index(["order_dt"])

In [368]:
model_andl_12th=ARIMA(df_andl_12['12th'],order=(1,1,1))
model_andl_12th_fit=model_andl_12th.fit()
model_andl_12th_forecast= model_andl_12th_fit.forecast(steps = 8)[0]
model_andl_12th_forecast

array([1.73557967, 1.69764553, 1.69769347, 1.70411106, 1.71159685,
       1.71926178, 1.72695675, 1.73465676])

In [369]:
df_andl_13 = pd.read_excel("ANNANDALE.xlsx")
df_andl_13["order_dt"] = pd.to_datetime(df_andl_13["order_dt"],infer_datetime_format=True)
df_andl_13= df_andl_13.set_index(["order_dt"])

In [370]:
model_andl_13th=ARIMA(df_andl_13['13th'],order=(1,1,1))
model_andl_13th_fit=model_andl_13th.fit()
model_andl_13th_forecast= model_andl_13th_fit.forecast(steps = 8)[0]
model_andl_13th_forecast

array([2.66057826, 3.09809573, 3.22092175, 3.2627782 , 3.28380131,
       3.29946405, 3.31374757, 3.32767622])

In [371]:
df_andl_14 = pd.read_excel("ANNANDALE.xlsx")
df_andl_14["order_dt"] = pd.to_datetime(df_andl_14["order_dt"],infer_datetime_format=True)
df_andl_14= df_andl_14.set_index(["order_dt"])

In [372]:
model_andl_14th=ARIMA(df_andl_14['14th'],order=(1,1,1))
model_andl_14th_fit=model_andl_14th.fit()
model_andl_14th_forecast= model_andl_14th_fit.forecast(steps = 8)[0]
model_andl_14th_forecast

array([1.7732226 , 1.85086716, 1.86484745, 1.87300074, 1.8806207 ,
       1.88819185, 1.89575853, 1.9033248 ])

In [373]:
df_andl_15 = pd.read_excel("ANNANDALE.xlsx")
df_andl_15["order_dt"] = pd.to_datetime(df_andl_15["order_dt"],infer_datetime_format=True)
df_andl_15= df_andl_15.set_index(["order_dt"])

In [374]:
model_andl_15th=ARIMA(df_andl_15['15th'],order=(1,1,1))
model_andl_15th_fit=model_andl_15th.fit()
model_andl_15th_forecast= model_andl_15th_fit.forecast(steps = 8)[0]
model_andl_15th_forecast

array([3.53558198, 3.54036556, 3.55428503, 3.56838238, 3.5824832 ,
       3.59658409, 3.61068497, 3.62478586])

In [375]:
df_andl_16 = pd.read_excel("ANNANDALE.xlsx")
df_andl_16["order_dt"] = pd.to_datetime(df_andl_16["order_dt"],infer_datetime_format=True)
df_andl_16= df_andl_16.set_index(["order_dt"])

In [376]:
model_andl_16th=ARIMA(df_andl_16['16th'],order=(1,1,1))
model_andl_16th_fit=model_andl_16th.fit()
model_andl_16th_forecast= model_andl_16th_fit.forecast(steps = 8)[0]
model_andl_16th_forecast

array([4.33581496, 4.34718545, 4.36698788, 4.38683274, 4.40667781,
       4.42652288, 4.44636796, 4.46621303])

In [377]:
df_andl_17 = pd.read_excel("ANNANDALE.xlsx")
df_andl_17["order_dt"] = pd.to_datetime(df_andl_17["order_dt"],infer_datetime_format=True)
df_andl_17= df_andl_17.set_index(["order_dt"])

In [378]:
model_andl_17th=ARIMA(df_andl_17['17th'],order=(1,1,1))
model_andl_17th_fit=model_andl_17th.fit()
model_andl_17th_forecast= model_andl_17th_fit.forecast(steps = 8)[0]
model_andl_17th_forecast

array([4.2427505 , 4.2681181 , 4.28632121, 4.30448215, 4.32264284,
       4.34080354, 4.35896423, 4.37712492])

In [379]:
df_andl_18 = pd.read_excel("ANNANDALE.xlsx")
df_andl_18["order_dt"] = pd.to_datetime(df_andl_18["order_dt"],infer_datetime_format=True)
df_andl_18= df_andl_18.set_index(["order_dt"])

In [380]:
model_andl_18th=ARIMA(df_andl_18['18th'],order=(1,1,1))
model_andl_18th_fit=model_andl_18th.fit()
model_andl_18th_forecast= model_andl_18th_fit.forecast(steps = 8)[0]
model_andl_18th_forecast

array([3.40782609, 3.37656383, 3.3964319 , 3.41034602, 3.42495345,
       3.43948015, 3.45401625, 3.46855125])

In [381]:
df_andl_19 = pd.read_excel("ANNANDALE.xlsx")
df_andl_19["order_dt"] = pd.to_datetime(df_andl_19["order_dt"],infer_datetime_format=True)
df_andl_19= df_andl_19.set_index(["order_dt"])

In [382]:
model_andl_19th=ARIMA(df_andl_19['19th'],order=(1,1,1))
model_andl_19th_fit=model_andl_19th.fit()
model_andl_19th_forecast= model_andl_19th_fit.forecast(steps = 8)[0]
model_andl_19th_forecast

array([3.42175506, 3.87032455, 4.01959355, 4.07681352, 4.10572408,
       4.12592815, 4.14345457, 4.16015748])

In [383]:
df_andl_20 = pd.read_excel("ANNANDALE.xlsx")
df_andl_20["order_dt"] = pd.to_datetime(df_andl_20["order_dt"],infer_datetime_format=True)
df_andl_20= df_andl_20.set_index(["order_dt"])

In [384]:
model_andl_20th=ARIMA(df_andl_20['20th'],order=(1,1,1))
model_andl_20th_fit=model_andl_20th.fit()
model_andl_20th_forecast= model_andl_20th_fit.forecast(steps = 8)[0]
model_andl_20th_forecast

array([3.23304608, 3.14440403, 3.16657087, 3.1794476 , 3.19310321,
       3.20669352, 3.2202893 , 3.23388463])

In [385]:
data_andl =[k for k in zip(model_andl_9th_forecast,model_andl_10th_forecast,model_andl_11th_forecast,
                          model_andl_12th_forecast,model_andl_13th_forecast,model_andl_14th_forecast,model_andl_15th_forecast,
                          model_andl_16th_forecast,model_andl_17th_forecast,model_andl_18th_forecast,model_andl_19th_forecast,
                          model_andl_20th_forecast)]

In [386]:
df_andl = pd.DataFrame(data_andl)
df_andl.head(10)

0         1         2         3         4         5         6   \
0  1.215432  2.499462  2.462199  1.735580  2.660578  1.773223  3.535582   
1  0.724412  2.519148  2.486723  1.697646  3.098096  1.850867  3.540366   
2  0.924182  2.527641  2.495979  1.697693  3.220922  1.864847  3.554285   
3  0.844313  2.535873  2.505650  1.704111  3.262778  1.873001  3.568382   
4  0.877645  2.544099  2.515310  1.711597  3.283801  1.880621  3.582483   
5  0.865152  2.552325  2.524970  1.719262  3.299464  1.888192  3.596584   
6  0.871209  2.560551  2.534631  1.726957  3.313748  1.895759  3.610685   
7  0.869757  2.568777  2.544291  1.734657  3.327676  1.903325  3.624786   

         7         8         9         10        11  
0  4.335815  4.242750  3.407826  3.421755  3.233046  
1  4.347185  4.268118  3.376564  3.870325  3.144404  
2  4.366988  4.286321  3.396432  4.019594  3.166571  
3  4.386833  4.304482  3.410346  4.076814  3.179448  
4  4.406678  4.322643  3.424953  4.105724  3.193103  
5  4.426523  4.340804  3.439480  4.125928  3.206694  
6  4.446368  4.358964  3.454016  4.143455  3.220289  
7  4.466213  4.377125  3.468551  4.160157  3.233885

In [387]:
df_andl.to_excel('andl_2m_9m_test.xlsx')